import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";

import { Nunito_Sans } from "next/font/google";
// import DashboardHeader from "./(participants)/_components/dashboard-header";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Conwalls",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className={`font-nunito antialiased`}>
        <AuthProvider>
          <AppProvider>
            {/* <DashboardHeader/> */}

            {children}
            <Toaster />

          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
